name: CI Pipeline

# запустится при пулреквесте на мейн
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest httpx
        if [ -f informer/requirements.txt ]; then pip install -r informer/requirements.txt; fi

    - name: python linter
      run: |
        flake8 informer --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 informer --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: run python tests
      run: |
        pytest informer/

    - name: Build C++ Aquarium
      run: |
        cd bulbul
        g++ -std=c++17 src/*.cpp -o aquarium_app -pthread
    - name: Run C++ Unit Tests
      run: |
          cd bulbul
          g++ -std=c++17 -Isrc src/world.cpp src/actor.cpp src/entity.cpp src/fishes.cpp src/canvas.cpp src/bubble.cpp tests/test_world.cpp -o run_tests -pthread
          ./run_tests